spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ecommerce;encrypt=true;trustServerCertificate=true
    username: sa
    password: APPsqt!312
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  security:
    user:
      name: admin
      password: admin123
    secret-key: 0JmBkoPTLa8UosMH4+kQZ5Jvk8uJ0vMVz9Sit3OPAlQ=
    validity: 3600000

  jackson:
    serialization:
      INDENT_OUTPUT: true



server:
  port: 8080
